# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.CharField(db_index=True, max_length=3, null=True)),
                ('o', models.CharField(db_index=True, max_length=64, null=True)),
                ('cn', models.CharField(db_index=True, max_length=64, null=True)),
                ('sn', models.CharField(db_index=True, max_length=40, null=True)),
                ('ea', models.CharField(db_index=True, max_length=255, null=True)),
                ('filename', models.CharField(db_index=True, default=b'', max_length=255)),
                ('body', models.TextField(null=True)),
            ],
            options={
                'db_table': 'certs',
            },
        ),
    ]
